/**
 * Stellarator - Creates procedural systems for Kopernicus
 * Copyright (c) 2016 Thomas P.
 * Licensed under the Terms of the MIT License
 */

using System;

namespace Stellarator
{
    public class Templates
    {
        /// <summary>
        /// All Stock bodies that we can use as a template
        /// </summary>
        public static String[] StockTemplates = { "Moho", "Eve", "Gilly", "Mun", "Minmus", "Duna", "Ike", "Dres", "Laythe", "Vall", "Tylo", "Bop", "Pol", "Eeloo" };

        /// <summary>
        /// A header that is added to each config file
        /// </summary>
        public const String header = "// Generated by Stellarator (https://github.com/Kopernicus/Stellarator)\n// License: MIT (Configs and Code); All Rights Reserved (Art Assets)\n// System Seed: {0}\n\n";

        /// <summary>
        /// The timewarplimits of Kerbin
        /// </summary>
        public static Int32[] KerbinTimewarplimits = {0, 30000, 30000, 60000, 120000, 240000, 480000, 600000};

        /// <summary>
        /// The timewarplimits of Sun
        /// </summary>
        public static Double[] SunTimewarplimits = { 0, 3270000, 3270000, 6540000, 1.308E+07, 2.616E+07, 5.232E+07, 6.54E+07 };
    }
}